export let gemsArr = [
    {
        name:'石榴石',
        imgSrc:'./img/gems/stone_id_1.jpg'
    },
    {
        name:'紫水晶',
        imgSrc:'./img/gems/stone_id_2.jpg'
    },
    {
        name:'海藍寶石',
        imgSrc:'./img/gems/stone_id_3.jpg'
    },
    {
        name:'鑽石',
        imgSrc:'./img/gems/stone_id_4.jpg'
    },
    {
        name:'祖母綠',
        imgSrc:'./img/gems/stone_id_5.jpg'
    },
    {
        name:'月光石',
        imgSrc:'./img/gems/stone_id_6.jpg'
    },
    {
        name:'紅寶石',
        imgSrc:'./img/gems/stone_id_7.jpg'
    },
    {
        name:'貴橄欖石',
        imgSrc:'./img/gems/stone_id_8.jpg'
    },
    {
        name:'藍寶石',
        imgSrc:'./img/gems/stone_id_9.jpg'
    },
    {
        name:'碧璽',
        imgSrc:'./img/gems/stone_id_10.jpg'
    },
    {
        name:'托帕石',
        imgSrc:'./img/gems/stone_id_11.jpg'
    },
    {
        name:'坦桑石',
        imgSrc:'./img/gems/stone_id_12.jpg'
    }
] 